---
- name: Loop example
  hosts: webservers
  vars:
    packages:
      - httpd
      - mariadb
      - xclock
  tasks: 
    - name: Install a single Package 
      yum:
        name: httpd
        state: present
      register: one_element_output


    - name: Install packages
      yum:
        name: "{{ paket }}"
        state: present
      loop: "{{ packages | default([]) }}"
      register: multiple_element_output
      loop_control:
        loop_var: paket
        index_var: index

    - name: Debug - one element
      debug: 
        msg: "{{ one_element_output }}"

    - name: Debug - multiple element
      debug: 
        msg: "{{ multiple_element_output }}"
