---
- name: Lets use Roles
  hosts: webservers
  tasks:
    - name: Include install_apache role
      vars:
        firewall_services_to_be_enabled:
          - http
          - https
        firewall_ports_to_be_enabled:
          - 80/tcp
          - 443/tcp
      include_role:
        name: install_apache
