---
- name: Test Windows server
  hosts: windows_hosts
  gather_facts: false
  vars:
    skip_debug: false
  tasks:
    - name:  Gather some info
      setup:
      
    - name: Print some message
      debug:
        msg: " All conditions are true"
      when: 
        - "'Windows' in ansible_distribution"
        - ansible_memtotal_mb >= 4096 and ansible_architecture == '64-bit'
        - not skip_debug

