---
- name: Delegation example
  hosts: rheldev
  tasks:
    - name: remote running process
      shell: "ps -ef | grep -i tower"
      register: remote_process

    - name: Print remote process output
      debug:
        msg: "{{ remote_process.stdout }}"

    - name: local  running process
      become: false
      shell: "ps -ef | grep -i tower"
      delegate_to: localhost
      register: delegated_process

    - name: Print delegated  process output
      debug:
        msg: "{{ delegated_process.stdout }}"
