---
- name: delegate facts
  hosts: rheldev 
  tasks:
    - name: Create a temporary inventory
      no_log: true 
      add_host:
        name: rheldev2
        group: temporary_group
        ansible_host: 192.168.1.183
        ansible_user: devops
        ansible_password: redhat
        ansible_become_method: sudo
        ansible_become_pass: redhat
        ansible_become: yes

    - name: Collect facts
      setup:
      delegate_to: rheldev2
      delegate_facts: yes

    - name: Print ip info
      debug:
        msg: "{{ ansible_default_ipv4.address }}"
