---
- name: Async example
  hosts: webservers
  gather_facts: false
  tasks:
    - name: Simulate long running task
      command: /bin/sleep 45
      async: 300
      poll: 0 
      register: long_running_job
      
    - name: gather facts
      setup: 

    - name: Print ip info
      debug:
        msg: "{{ ansible_default_ipv4.address }}"

    - name: Wait for asynchronous job to end
      async_status:
        jid: '{{ long_running_job.ansible_job_id }}'
      register: job_result
      until: job_result.finished
      retries: 30
      delay: 5 
