- name: Just test new eei for vmware collection
  hosts: localhost
  gather_facts: yes
  vars:
#    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Gather VM info
      community.vmware.vmware_guest_info:
        hostname: '{{ lookup("env", "VMWARE_HOST") }}'
        username: '{{ lookup("env", "VMWARE_USER") }}'
        password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
        validate_certs: False
        datacenter: "KonsaltDC"
        folder: /
        name: "{{ vmname }}"
        schema: "vsphere"
        #properties: ["config.hardware.memoryMB", "config.hardware.numCPU", "guest.disk", "overallStatus"]
        #properties: ["config.hardware.memoryMB", "config.hardware.numCPU", "guest.guestFullName", "resourcePool.summary.name","guest.hostName", "name", "guest.disk", "overallStatus"]
      register: vm_info

    - name: Read data from host
      ansible.builtin.debug:
        msg: "{{ lookup('file','/mydata/example.txt') }}"

    - name: Write content to a new file
      ansible.builtin.copy:
        dest: "/mydata/example_write.txt"
        content: "{{ vm_info | to_yaml }}"


    - name: Read data from  newly created file
      ansible.builtin.debug:
        msg: "{{ lookup('file','/mydata/example_write.txt') }}"
