- name: Just test new eei for vmware collection
  hosts: localhost
  gather_facts: yes
  vars:
#    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Gather VM info
      community.vmware.vmware_guest_info:
        hostname: '{{ lookup("env", "VMWARE_HOST") }}'
        username: '{{ lookup("env", "VMWARE_USER") }}'
        password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
        validate_certs: False
        datacenter: "KonsaltDC"
        folder: /RedHat
        name: "satellite"
        schema: "vsphere"
        #properties: ["config.hardware.memoryMB", "config.hardware.numCPU", "guest.disk", "overallStatus"]
        #properties: ["config.hardware.memoryMB", "config.hardware.numCPU", "guest.guestFullName", "resourcePool.summary.name","guest.hostName", "name", "guest.disk", "overallStatus"]
      register: vm_info
