---
version: 1
build_arg_defaults:
  #EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:latest'
  EE_BASE_IMAGE: 'automationhub.konsalt.info/ee-29-rhel8:latest'
  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8'
dependencies:
  #galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  #prepend:
  #  - COPY krb5.conf /etc/krb5.conf
  #  - COPY ansible.cfg /etc/ansible/ansible.cfg
  #append:
  #  - COPY automationhub-root.crt /etc/pki/ca-trust/source/anchors/automationhub-root.crt
  #  - RUN update-ca-trust
  #  - RUN microdnf install crypto-policies-scripts
  #  - RUN update-crypto-policies --set DEFAULT:AD-SUPPORT
